---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-app
  namespace: argocd
spec:
  destination:
    namespace: webapp
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: build.enabled
          value: "false"
        - name: deploy.route.enabled
          value: "false"
        - name: image.name
          value: val717/k8s-app:1.0
    chart: k8s-web
    repoURL: https://github.com/val1707/docker-prod.git
    targetRevision: 1.0
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
