apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-app
  name: k8s-app
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-app
  strategy: {}
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
      - image: 341253804405.dkr.ecr.eu-central-1.amazonaws.com/blox:latest
        name: k8s-app
        resources: {}
