apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-app
  name: k8s-app
  namespace: webapp
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30088
  selector:
    app: k8s-app


